export const storeProducts = [
  //men, women supplement
  {
    id: 1,
    title: "Alaska Omega - 3.6.9",
    img: "/img/alaska_deep_sea.jpg",
    price: 9500,
    company: "Omega",
    info:
    "Dietary supplements to maintains heart, skin, immune system and brain health",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Alaska Omega - 3",
    img: "/img/Alaska Omega-3.jpg",
    price: 8500,
    company: "",
    info:
    "Dietary supplements to maintains heart, skin, eye and brain health",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Alfalfa - FAME",
    img: "/img/alfalfa fame.jpg",
    price: 5500,
    company: "FAME",
    info:
    "Dietary supplements to maintains heart, skin, eye and brain health",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Anlene large",
    img: "/img/anlene large.jpg",
    price: 12500,
    company: "Anlene",
    info:
      "Nutritional milk powder supplement for adults",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Appletec - FAME",
    img: "/img/appletec.jpg",
    price: 6150,
    company: "FAME",
    info:
      "schemic heart disease, Arthritis and a variety of inflammation, Tumor formation",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Arthrostop Rapid",
    img: "/img/arthrotec.jpg",
    price: 2700,
    company: "Arthrostop",
    info:
      "Reduction of joint inflammation & relief of pain associated w/ arthritis & OA.",
    inCart: false,
    count: 0,
    total: 0,
  },
  // Kid / Teenaged supplement
  {
    id: 7,
    title: "Appeton A-Z Kid's Vitamin C",
    img: "/img/APPETONA-ZKID_SVITAMINCPASTILLES5_S_723x715.jpg",
    price: 8800,
    company: "Appeton",
    info:
      "Used as dietary supplements.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Appeton Essentials Teengrow",
    img: "/img/appeton teengrow essencials.jpg",
    price: 12800,
    company: "Appeton",
    info:
    "Used as dietary supplements.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Appeton Hi-Q Taurine With DHA Tablet",
    img: "/img/appeton multivita hi-q.jpg",
    price: 16200,
    company: "Appeton",
    info:
    "Used as dietary supplements.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Appeton Lysine with Probiotics Tablet",
    img: "/img/appeton multivita lysine.jpg",
    price: 15400,
    company: "Appeton",
    info:
    "Used as dietary supplements.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Appeton Plus Infant Drops",
    img: "/img/appeton infant drop.jpg",
    price: 11000,
    company: "Appeton",
    info:
    "Used as dietary supplements.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Appeton Taurine Syrup",
    img: "/img/appeton taurine syrup.jpg",
    price: 12200,
    company: "Appeton",
    info:
    "Used as dietary supplements.",
    inCart: false,
    count: 0,
    total: 0,
  },
  // Sleep aid 
  {
    id: 13,
    title: "Herbal Fresh - FAME",
    img: "/img/herbal fame.jpg",
    price: 5100,
    company: "FAME",
    info:
      "Mental refreshment, mild to moderate depression and secondary symptoms like headache, sweating, palpitation, anxiety and insomnia",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Herbal Sleep - FAME",
    img: "/img/herbalsleep fame.jpg",
    price: 7150,
    company: "FAME",
    info:
"nsomnia, Stress and anxiety, Neuro-fatigue",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Melatonin",
    img: "/img/natrol-melatonin-100ct-10mgmaximum-tablet-fastdissolve-strawberry-047469071509-2.png",
    price: 9400,
    company: "Melatonin",
    info:
"Promotes restful sleep and wake up fresh.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "Somino Sleep",
    img: "/img/Somino Sleep.jpg",
    price: 12000,
    company: "Somino",
    info:
"Promotes restful sleep and wake up fresh.",
    inCart: false,
    count: 0,
    total: 0,
  },
  // Fever 
  {
    id: 17,
    title: "Axcel Paracetamol-120 Syrup (Cherry Flavour)",
    img: "/img/Axcel Paracetamol-120 Syrup (Cherry Flavour).jpg",
    price: 2000,
    company: "Axcel",
    info:
"Cold, Fever, Headache, Body aches, Toothache",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: "Biogesic Suspension for kids - 120mg (Strawberry)",
    img: "/img/Biogesic Suspension for kids - 120mg (Strawberry).jpg",
    price: 2760,
    company: "Biogesic",
    info:
    "Cold, Fever, Headache, Body aches, Toothache",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: "Axcel Paracetamol-120 Syrup (Cherry Flavour)",
    img: "/img/Axcel Paracetamol-250 Syrup (Orange Flavour).jpg",
    price: 2750,
    company: "Axcel",
    info:
    "Cold, Fever, Headache, Body aches, Toothache",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: "Alaxan FR",
    img: "/img/Alaxan FR.jpg",
    price: 1300,
    company: "Alaxan",
    info:
"Relief of mild to moderate pain of musculoskeletal origin , Traumatic injection-dripuries, Tension headache",
    inCart: false,
    count: 0,
    total: 0,
  },
  //  Cough 
  {
    id: 21,
    title: "Atussin Tablet",
    img: "/img/Atussin Tablet.jpg",
    price: 600,
    company: "Atussin",
    info:
"Cough, Chest congestion, Cold, Asthma, Breathing disorders, Sinusitis, and Bronchitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 22,
    title: "Bronchest",
    img: "/img/IVAugmentin.png",
    price: 2400,
    company: "Bronchest",
    info:
    "Cough, Chest congestion, Cold, Asthma, Breathing disorders, Sinusitis, and Bronchitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: "Ascoril Expectorant",
    img: "/img/ASCORIL-EXPECTORANT-200ML.jpg",
    price: 2100,
    company: "Ascoril",
    info:
"Wet cough, Chest congestion, Cold, Asthma, Breathing disorders, Sinusitis, and Bronchitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 24,
    title: "Baby Cough Syrup",
    img: "/img/IVAugmentin.png",
    price: 1000,
    company: "Zifam",
    info:
    "Wet cough, Chest congestion, Cold, Asthma, Breathing disorders, Sinusitis, and Bronchitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  //  Sneezing , Sinaus Congestion
  {
    id: 25,
    title: "Alerday",
    img: "/img/OralAmoxicillin.png",
    price: 3800,
    company: "Alerday",
    info:
"Seasonal allergic rhinitis (hay fever), sneezing, itching, runny or blocked nose, red and watery eyes, Chronic Idiopathic Urticaria",    
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 26,
    title: "Allercet",
    img: "/img/Allercet.jpg",
    price: 400,
    company: "Allercet",
    info:
    "Seasonal allergic rhinitis (hay fever), sneezing, itching, runny or blocked nose, red and watery eyes, Chronic Idiopathic Urticaria",    
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 27,
    title: "Burmeton Tablets",
    img: "/img/OralFlumox1.png",
    price: 1000,
    company: "Burmeton",
    info:
    "Seasonal allergic rhinitis (hay fever), sneezing, itching, runny or blocked nose, red and watery eyes, Chronic Idiopathic Urticaria",    
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 28,
    title: "Cetrine",
    img: "/img/Cetrine.jpg",
    price: 2550,
    company: "Cetrine",
    info:
    "Seasonal allergic rhinitis (hay fever), sneezing, itching, runny or blocked nose, red and watery eyes, Chronic Idiopathic Urticaria",    
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 29,
    title: "Amlorat",
    img: "/img/Amlorat.jpg",
    price: 300,
    company: "Amlorat",
    info:
    "Seasonal allergic rhinitis (hay fever), sneezing, itching, runny or blocked nose, red and watery eyes, Chronic Idiopathic Urticaria",    
    inCart: false,
    count: 0,
    total: 0,
  },
  // 
  {
    id: 30,
    title: "Cetrizet",
    img: "/img/cetrizet-tablets-500x500.jpg",
    price: 1000,
    company: "Cetrizet",
    info:
    "Seasonal allergic rhinitis (hay fever), sneezing, itching, runny or blocked nose, red and watery eyes, Chronic Idiopathic Urticaria",    
    inCart: false,
    count: 0,
    total: 0,
  },
  // Eye ,ear, nose and throat
  {
    id: 31,
    title: "Dexoptic-N Eye Drops",
    img: "/img/Dexoptic-N Eye Drops.jpg",
    price: 3100,
    company: "Dexoptic",
    info:
"Use in many disorders of the anterior segment of the eye due to or complicated by infection, as in vernal, allergic and non-purulent conjunctivitis, keratitis of different forms; iritis, cyclitis, and in superficial and chemical burns of the cornea.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 32,
    title: "Daktarin",
    img: "/img/daktarin-creme-creme-30g.096807.jpg",
    price: 3950,
    company: "Daktarin",
    info:
"Fungal infections of the mouth and throat (e.g. thrush), especially in children.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 33,
    title: "Chericof Lozenges (Orange Flavour)",
    img: "/img/OralPantocid.png",
    price: 700,
    company: "Chericof",
    info:
"Sore throat, Throat irritation",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 34,
    title: "Betadine Gargle & Mouthwash",
    img: "/img/Betadine Gargle & Mouthwash.jpg",
    price: 6500,
    company: "Betadine",
    info:
"Gargle and Mouthwash to kill bacteria, viruses, fungi, spres and protozoa",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 35,
    title: "ii Care",
    img: "/img/iicarae-4.jpg",
    price: 11600,
    company: "Care",
    info:
"Help maintain healthy eyesight and prevent age-related eye diseases.",
    inCart: false,
    count: 0,
    total: 0,
  },
  // Injection and disease
  {
    id: 36,
    title: "Scalp vein set (butterfly needle)",
    img: "/img/Scalp vein set (butterfly needle).jpg",
    price: 5340,
    company: "Scalap",
    info:
      "Scalp vein set (butterfly needle)",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 37,
    title: "infusion set",
    img: "/img/Infusion Set.jpg",
    price: 3750,
    company: "Zifam",
    info:
"infusion set",
    inCart: false,
    count: 0,
    total: 0,
  },
  //  allergy and skin disease
  {
    id: 38,
    title: "betatine solution",
    img: "/img/Betadine Solution.jpg",
    price: 3650,
    company: "betatine solution",
    info:
"Antiseptic used for skin disinfection",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 39,
    title: "Bioplacenton Jelly",
    img: "/img/OralPantocid.png",
    price: 2600,
    company: "Bioplaceton",
    info:
"For the management of burns, chronic ulcers, slow healing and slow granulating wounds, decubital ulcers, eczema pyoderma, impetigo, furunculosis, and other skin infection.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 40,
    title: "Burscabe Lotion",
    img: "/img/Bludrox-P DT.jpg",
    price: 1800,
    company: "Burscabe Lotion",
    info:
"Scabicide, Pediculicide",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 41,
    title: "Acyclovir STADA 400mg",
    img: "/img/Bioplacenton Jelly.jpg",
    price: 1000,
    company: "Acyclovir STADA",
    info:
      "Recurrence of herpes simplex virus (HSV) episodes (including genital herpes) and to treat varicella zoster virus (VZV) diseases (including chicken pox and shingles).",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 42,
    title: "Bet-N Cream",
    img: "/img/Bet-N Cream.jpg",
    price: 950,
    company: "Bet-N Cream",
    info:
      "Skin infections such as Eczema, Dermatitis, Psoriasis",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 43,
    title: "Betadine Dry Powder Spray",
    img: "/img/betadine_dry_powder_spray_55g.jpg",
    price: 7700,
    company: "Betadine Dry Powder Spray",
    info:
      "Antiseptic used for skin disinfection",
    inCart: false,
    count: 0,
    total: 0,
  },
  // Instrument , device and accessories
  {
    id: 44,
    title: "10cmx10cm Gauze Swab (Sterile) - 4x25 Itemst",
    img: "/img/10cmx10cm Gauze Swab (Sterile) - 4x25 Items.jpg",
    price: 9500,
    company: "Gauze Swab",
    info:
      "Absorbant Gauze Cloth",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 45,
    title: "Accu-Chek Active Test Strips 50's",
    img: "/img/accu-chek-active-test-strips-50-s-500x500.jpg",
    price: 18500,
    company: "Zifam",
    info:
      "Test strips for Accu-Chek Active nano blood glucose meter.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 46,
    title: '2" Bandage medx',
    img: "/img/bantage_2in_1.jpg",
    price: 700,
    company: "medx",
    info:
    "Test strips for Accu-Chek Active nano blood glucose meter.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 47,
    title: '3" Bandage medx',
    img: "/img/3Bandage.jpg",
    price: 850,
    company: "medx",
    info:
    "Test strips for Accu-Chek Active nano blood glucose meter.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 48,
    title: "Belladonna Plaster",
    img: "/img/Belladonna Plaster.jpg",
    price: 6550,
    company: "Belladonna",
    info:
"Plaster for muscle pains and aches",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 49,
    title: "Accu-Chek Perfoma Test Strips 25's",
    img: "/img/Accu-Chek Perfoma Test Strips.jpg",
    price: 14300,
    company: "Perfoma",
    info:
"Test strips for Accu-Chek Performa nano blood glucose meter.",
    inCart: false,
    count: 0,
    total: 0,
  },
  // Myanmar traditional medicine
  {
    id: 50,
    title: "ကေသီပန် - Kaythy Pan",
    img: "/img/kathypan_1.jpg",
    price: 2150,
    company: "ကေသီပန်",
    info:
"သွေးပုပ်ချဆေး",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 51,
    title: "တော့(ပ်)ယူနန် - Top Yunan",
    img: "/img/တော့(ပ်)ယူနန် - Top Yunan.jpg",
    price: 850,
    company: "တော့(ပ်)ယူနန်",
    info:
"အကြောအဆစ်ကိုက်လိမ်းဆေးအဆီ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 52,
    title: "ဆရာမိုး - Sayar Moe",
    img: "/img/Sayar Moe.jpg",
    price: 750,
    company: "ဆရာမိုး - Sayar Moe",
    info:
"ဝမ်းမှန်ဆေး",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 53,
    title: "ဆရာခို - Sayar Kho",
    img: "/img/Sayar Kho.jpg",
    price: 150,
    company: "ဆရာခို",
    info:
"အနာလိမ်းဆေး",
    inCart: false,
    count: 0,
    total: 0,
  },
  // infection
  {
    id: 54,
    title: "Augmentin 625",
    img: "/img/Augmentin 625.jpg",
    price: 9900,
    company: "Augmentin",
    info:
      "Bacterial Infectious disease",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 55,
    title: "Benda 500",
    img: "/img/Benda 500.jpg",
    price: 1000,
    company: "Benda",
    info:
      "Treatment of enterobiasis, ascariasis, trichuriasis, ancylostomiasis in single or mixed infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 56,
    title: "Betadine Solution",
    img: "/img/Betadine Solution.jpg",
    price: 3650,
    company: "Beta",
    info:
      "Antiseptic used for skin disinfection",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 57,
    title: "Bludrox-P DT",
    img: "/img/Bludrox-P DT.jpg",
    price: 1300,
    company: "Bludrox",
    info:
      "Bacterial Infectious disease",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 58,
    title: "Blumox-250 DT",
    img: "/img/Blumox-250 DT.jpg",
    price: 2150,
    company: "Beta",
    info:
      "Bacterial Infectious disease",
    inCart: false,
    count: 0,
    total: 0,
  },
  //
  {
    id: 59,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 60,
    title: "ZIFAM  CS1 / CS2",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 61,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 62,
    title: "IV Amikacin Zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 63,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 64,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 65,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 66,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 67,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 68,
    title: "Oral Amoxicillin",
    img: "/img/OralAmoxicillin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Amoxicillin is used to treat bacterial infections in many different parts of the body. It is also used with other medicines (e.g., clarithromycin, lansoprazole) to treat H. pylori infection and duodenal ulcers.Amoxicillin belongs to the group of medicines known as penicillin antibiotics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 69,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 70,
    title: "Flumox 500mg Vial",
    img: "/img/OralFlumox1.png",
    price: 5000,
    company: "Zifam",
    info:
      "Amoxicillin is a semisynthetic antibiotic, an analog of ampicillin, with a broad spectrum of bactericidal activity against many gram-positive and gram-negative microorganisms. Chemically it is ohydrate for oral use and as sodium salt for parenteral use.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 71,
    title: "Oral paracetamol",
    img: "/img/OralParacetamol.png",
    price: 5000,
    company: "Zifam",
    info:
      "CLOFEN PLUS is used in the Management of osteoarthritis, rheumatoid arthritis and ankylosing spondylitis. NSAIDs are used for the relief of mild to moderate pain, minor febrile conditions and for acute and chronic inflammatory disorders such as osteoarthritis, rheumatoid arthritis, juvenile chronic arthritis and ankylosing spondylitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 72,
    title: "Oral diclofenac",
    img: "/img/OralDiclofenac.png",
    price: 5000,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 73,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 74,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 75,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 76,
    title: "ZIFAM  CS1 / CS2",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 77,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 78,
    title: "IV Amikacin Zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 79,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 80,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 81,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 82,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 83,
    title: "Oral Amoxicillin",
    img: "/img/OralAmoxicillin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Amoxicillin is used to treat bacterial infections in many different parts of the body. It is also used with other medicines (e.g., clarithromycin, lansoprazole) to treat H. pylori infection and duodenal ulcers.Amoxicillin belongs to the group of medicines known as penicillin antibiotics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 84,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 85,
    title: "Flumox 500mg Vial",
    img: "/img/OralFlumox1.png",
    price: 5000,
    company: "Zifam",
    info:
      "Amoxicillin is a semisynthetic antibiotic, an analog of ampicillin, with a broad spectrum of bactericidal activity against many gram-positive and gram-negative microorganisms. Chemically it is ohydrate for oral use and as sodium salt for parenteral use.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 86,
    title: "Oral paracetamol",
    img: "/img/OralParacetamol.png",
    price: 5000,
    company: "Zifam",
    info:
      "CLOFEN PLUS is used in the Management of osteoarthritis, rheumatoid arthritis and ankylosing spondylitis. NSAIDs are used for the relief of mild to moderate pain, minor febrile conditions and for acute and chronic inflammatory disorders such as osteoarthritis, rheumatoid arthritis, juvenile chronic arthritis and ankylosing spondylitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 87,
    title: "Oral diclofenac",
    img: "/img/OralDiclofenac.png",
    price: 5000,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 88,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 89,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 90,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 91,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 92,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 93,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 94,
    title: "Flumox 500mg Vial",
    img: "/img/OralFlumox1.png",
    price: 5000,
    company: "Zifam",
    info:
      "Amoxicillin is a semisynthetic antibiotic, an analog of ampicillin, with a broad spectrum of bactericidal activity against many gram-positive and gram-negative microorganisms. Chemically it is ohydrate for oral use and as sodium salt for parenteral use.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 95,
    title: "ZIFAM  CS1 / CS2",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 96,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 97,
    title: "IV Amikacin Zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 98,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 99,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 100,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 101,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 102,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 103,
    title: "Oral Amoxicillin",
    img: "/img/OralAmoxicillin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Amoxicillin is used to treat bacterial infections in many different parts of the body. It is also used with other medicines (e.g., clarithromycin, lansoprazole) to treat H. pylori infection and duodenal ulcers.Amoxicillin belongs to the group of medicines known as penicillin antibiotics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 104,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 105,
    title: "ZIFAM  CS1 / CS2",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 106,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 107,
    title: "IV Amikacin Zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 108,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 109,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 110,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 111,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 112,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 113,
    title: "Oral Amoxicillin",
    img: "/img/OralAmoxicillin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Amoxicillin is used to treat bacterial infections in many different parts of the body. It is also used with other medicines (e.g., clarithromycin, lansoprazole) to treat H. pylori infection and duodenal ulcers.Amoxicillin belongs to the group of medicines known as penicillin antibiotics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 114,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 115,
    title: "ZIFAM  CS1 / CS2",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 116,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 117,
    title: "IV Amikacin Zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 118,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 119,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 120,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 121,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 122,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 123,
    title: "Oral Amoxicillin",
    img: "/img/OralAmoxicillin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Amoxicillin is used to treat bacterial infections in many different parts of the body. It is also used with other medicines (e.g., clarithromycin, lansoprazole) to treat H. pylori infection and duodenal ulcers.Amoxicillin belongs to the group of medicines known as penicillin antibiotics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 124,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 125,
    title: "ZIFAM  CS1 / CS2",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 126,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 127,
    title: "IV Amikacin Zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 128,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 129,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "IV CS1",
  img: "/img/product-1.png",
  price: 4500,
  company: "Zifam",
  info:
    "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
  inCart: false,
  count: 0,
  total: 0,
};
// Next Page about Oral
